chore: better auto.retry attempt Tue Nov 11 08:58:32 EET 2025

diff --git a/.github/workflows/auto.retry.yml b/.github/workflows/auto.retry.yml
--- a/.github/workflows/auto.retry.yml
+++ b/.github/workflows/auto.retry.yml
@@ -81,5 +81,6 @@ jobs:
       - name: Skip retry
         if: steps.check.outputs.should_retry == 'false'
         run: |
-          echo "::warning::⚠️ Max retry attempts reached. Manual intervention required."
-          echo "::warning::View the failed run at: ${{ github.event.workflow_run.html_url }}"
+          echo "::error::⚠️ Max retry attempts reached. Manual intervention required."
+          echo "::error::View the failed run at: ${{ github.event.workflow_run.html_url }}"
+          exit 1
